server/api/index.js, server/api/products.js
=> first GET route

server/db/models/index.js, server/db/models/instrument.js
=> added instrument model

seed.js
=> Seed complete

client/store/index.js, server/api/products.js
=> reducers set up

client/app.js, client/components/AllProducts.js, client/components/AllProductsContainer.js, client/routes.js, server/api/products.js
=> AllProduct & AllProductContainer Component

client/components/SingleInstrument.js, client/components/SingleInstrumentContainer.js, client/reducers/selectedInstrument.js, package-lock.json
=> single instruments done

seed.js, server/db/models/category.js, server/db/models/index.js, server/db/models/instrument.js
=> created category table

client/components/SingleInstrumentContainer.js, server/api/instruments.js
=> routes are updated

client/reducers/selectedInstrument.js, client/routes.js, client/store/index.js
=> things kinda work

client/components/AllInstruments.js, client/routes.js, server/api/instruments.js
=> allinstruments images

client/app.js, client/containers/SingleInstrumentContainer.js, client/routes.js, public/index.html, server/db/models/instrument.js
=> working for the most part

client/components/UpdateInstrument.js, client/containers/UpdateInstrumentContainer.js, client/reducers/selectedInstrument.js, client/routes.js
=> updated things

client/components/UpdateInstrument.js, client/containers/UpdateInstrumentContainer.js, client/reducers/selectedInstrument.js, client/routes.js
=> working on update

client/app.js, client/components/allCategories.js, client/containers/AllCategoriesContainer.js, client/reducers/allCategories.js, client/routes.js, client/store/index.js, seed.js, server/api/categories.js, server/api/index.js, server/db/models/category.js
=> All categories

client/components/SingleInstrument.js, client/components/UpdateInstrument.js, client/containers/SingleInstrumentContainer.js, client/containers/UpdateInstrumentContainer.js, client/reducers/selectedInstrument.js, client/routes.js, server/api/instruments.js
=> PUT FINALLY WORKS HALLELUJAH

client/components/AllInstruments.js, client/components/SingleCategory.js, client/components/SingleInstrument.js, client/components/UpdateInstrument.js, client/components/allCategories.js, client/components/navbarcomp.js, public/index.html, public/style.css
=> All products view

client/components/SingleInstrument.js
=> fixed form

client/components/AllInstruments.js, client/components/Instruments.js, client/reducers/searchInput.js
=> allInstruments component has search functionality

server/db/models/index.js, server/db/models/order.js, server/db/models/orderInstrument.js
=> models created

client/components/SingleInstrument.js, client/containers/SingleCategoryContainer.js, client/containers/SingleInstrumentContainer.js, script/seed.js
=> category name now shows up

client/components/AuthLogin_form.js, client/components/AuthSignup_form.js, client/components/auth-form.js, client/components/user-home.js, client/store/user.js, server/api/users.js, server/auth/google.js, server/auth/index.js, server/db/models/user.js, server/index.js
=> signup and login welcomes user with first name

client/components/AddInstrumentsForm.js, client/components/AllInstruments.js, client/components/SingleInstrument.js, client/components/navbarcomp.js, client/containers/AllInstrumentsContainer.js, client/reducers/instruments.js, public/style.css
=> new instrument can be added via frontend

client/components/AllCategories.js, client/components/AllInstruments.js, client/components/navbarcomp.js, server/db/models/user.js
=> nav bar updated

client/components/navbarcomp.js, public/style.css
=> shopping cart img added

client/components/AllInstruments.js, client/components/SingleInstrument.js, client/components/auth-form.js, client/containers/AllInstrumentsContainer.js, client/containers/SingleInstrumentContainer.js
=> semi authentication

client/components/Cart.js, client/components/SingleInstrument.js, client/components/navbarcomp.js, client/containers/CartContainer.js, client/containers/SingleInstrumentContainer.js, client/reducers/cart.js, client/routes.js, client/store/index.js, public/style.css
=> Shopping cart

client/components/OrderHistory.js, client/containers/OrderHistoryContainer.js, client/reducers/orderHistory.js, client/store/index.js
=> Order history

client/components/SingleInstrument.js, client/store/index.js, server/db/models/index.js, server/db/models/instrument.js
=> order history & line order model/reducer

client/components/SingleInstrument.js
=> took out an uncessary render

client/reducers/cart.js
=> Add to Cart reducer/thunk created

client/components/SingleInstrument.js, client/components/UpdateInstrument.js, client/containers/SingleInstrumentContainer.js
=> small bug fix

client/components/AllUsers.js
=> add grid to users

client/components/SingleInstrument.js, client/containers/SingleInstrumentContainer.js, client/reducers/cart.js, server/api/cart.js, server/api/index.js, server/db/models/index.js, server/db/models/lineOrder.js, server/db/models/order.js
=> line order model

client/components/navbarcomp.js, server/api/cart.js
=> took out cart-router.use

client/components/AuthLogin_form.js, client/components/AuthSignup_form.js, client/components/auth-form.js, public/style.css
=> login forms look 10% better

client/constants/server.js, server/api/checkout.js, server/index.js
=> stripe payment checkout setup for backend

client/components/SingleCategory.js, client/containers/SingleCategoryContainer.js, script/seed.js
=> single category view and seed

client/components/AddInstrumentsForm.js, client/components/Cart.js, client/components/Checkout.js, client/components/Order.js, client/components/Payment.js, client/constants/server.js, client/containers/CheckoutContainer.js, client/reducers/allUsers.js, client/reducers/cart.js, client/reducers/checkout.js, client/routes.js, client/store/index.js, client/store/test.store.spec.js, server/api/checkout.js, server/api/index.js, server/api/order.js, server/db/models/model.spec.js
=> can add a purchase to Order Model

client/components/Cart.js, client/components/Checkout.js, client/components/OrderHistory.js, client/containers/CheckoutContainer.js, client/containers/OrderHistoryContainer.js, client/reducers/orderHistory.js, client/routes.js, server/api/checkout.js, server/api/order.js
=> New branch order history

client/components/Cart.js
=> fixed minor in cart

client/reducers/allUsers.js, client/store/user.js, server/api/users.js
=> delete user works

client/components/Cart.js, client/containers/CartContainer.js, client/reducers/cart.js, server/api/cart.js
=> finished cart

server/api/category.js, server/api/instruments.js, server/api/users.js
=> backend authorization not including order-history

client/components/AllUsers.js, client/components/Cart.js, client/components/Checkout.js, client/components/Order.js, client/components/OrderHistory.js, client/components/user-home.js, client/containers/CheckoutContainer.js, client/containers/OrderHistoryContainer.js, client/reducers/orderHistory.js, client/store/index.js, server/api/checkout.js, server/api/index.js, server/api/order.js, server/db/models/order.js
=> all orders_history renders on the front end

script/seed.js
=> more stuffs to sell

client/components/SingleInstrument.js, client/components/navbarcomp.js, client/containers/SingleInstrumentContainer.js, client/reducers/cart.js, client/reducers/selectedInstrument.js, public/style.css, server/api/cart.js
=> cart quantity and add specific amount

client/components/navbarcomp.js
=> cart quantity
